---
kind: pipeline
type: docker
name: python35

steps:
- name: test
  image: python:3.5-alpine3.8
  commands:
    - ./drone.sh

---
kind: pipeline
type: docker
name: python36

steps:
- name: test
  image: python:3.6-alpine3.8
  commands:
    - ./drone.sh

---
kind: pipeline
type: docker
name: python37

steps:
- name: test
  image: python:3.7-alpine3.8
  commands:
    - ./drone.sh
